### ISSUE TITLE
请求baidu的API接口里好多时候都提示未找到页面，同样的URL用原生的就可以得到请求结果，升级到0.2.7后出现的

### ISSUE THREAD

**Issue by lijunfeng** [guonaihong/gout#316]
如题。

**Comment by guonaihong** [comment]
可否发下url。

**Comment by lijunfeng** [comment]
![image](https://user-images.githubusercontent.com/3746302/133624957-3b92b9d7-ab04-4ff0-be9a-29dcdff37d7f.png)
很奇怪的一个问题，我看调用一步步检查了也没有找到啥问题。

**Comment by lijunfeng** [comment]
0.2.6没有问题，原生的也没有问题。升级到0.2.7后就这样了。我还原回去0.2.6后就正常了，没搞清啥问题。

**Comment by guonaihong** [comment]
恩， 我看下。

**Comment by lijunfeng** [comment]
https://api.map.baidu.com/weather/v1/?district_id=310100&data_type=all&ak=ffyu0pP8P6Ao0KYr8FTZwDgsOFiA1oYA

**Comment by lijunfeng** [comment]
这个ak是百度里申请的，暴露出来一会就得删除了，如果失效了你申请一个啊。

**Comment by guonaihong** [comment]
好的



---原始邮件---
发件人: "@***@***.***&gt;
发送时间: 2021年9月17日(周五) 上午10:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guonaihong/gout] 请求baidu的API接口里好多时候都提示未找到页面，同样的URL用原生的就可以得到请求结果，升级到0.2.7后出现的 (#316)




 
这个ak是百度里申请的，暴露出来一会就得删除了，如果失效了你申请一个啊。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guonaihong** [comment]
@lijunfeng 七月兄, 你看下 891749bb41966b9cd57eec2f9c27a8dfd2e5350b 这个commit可行. 我这边自己测过. 你那边确认下没问题就打个tag.

**Comment by guonaihong** [comment]
v0.2.8 tag已上

**Comment by lijunfeng** [comment]
这下没有问题了，我看一下0.2.7的处理细节。谢谢
